//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 4/19/2015 11:57:25 PM
namespace AGEAS_iteration1
{
    
    /// <summary>
    /// There are no comments for Model4Container in the schema.
    /// </summary>
    public partial class Model4Container : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new Model4Container object using the connection string found in the 'Model4Container' section of the application configuration file.
        /// </summary>
        public Model4Container() : 
                base("name=Model4Container", "Model4Container")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Model4Container object.
        /// </summary>
        public Model4Container(string connectionString) : 
                base(connectionString, "Model4Container")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Model4Container object.
        /// </summary>
        public Model4Container(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Model4Container")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
    }
}
